export const FETCH_ALL_STUDENTS = 'FETCH_ALL_STUDENTS'
export const FETCH_ONE_STUDENT  = 'FETCH_ONE_STUDENT'
export const STUDENT_UPDATED    = 'STUDENT_UPDATED'
export const STUDENT_CREATED    = 'STUDENT_CREATED'
